### ISSUE TITLE
Short description copied from Gibran’s “The Forerunner”

### ISSUE THREAD

**Issue by bentley** [standardebooks/khalil-gibran_the-madman#3]
*The Madman*’s short description is identical to *The Forerunner*’s:

> The second collection of poetry and short stories by Lebanese author Khalil Gibran.

According to the long description, *The Madman* is actually his first collection.

This sentence could use additional rewording as it violates the manual’s requirement that [a short description be a complete sentence](https://standardebooks.org/manual/1.5.0/9-metadata#9.6.1.1).

**Comment by acabal** [comment]
Thanks, this should be fixed now!
